config/routes.rb
Rails.application.routes.draw do
  concern :exportable, Blacklight::Routes::Exportable.new

  # redirects for legacy DLA Franklin links

  get 'index.html' => 'legacy_franklin#redirect_to_root', :format => false
  get 'record.html' => 'legacy_franklin#record', :format => false
  # blacklight_advanced_search has an /advanced route but we never use advanced.html (w/ the format)
  # so this is safe to list here.
  get 'advanced.html' => 'legacy_franklin#redirect_to_root', :format => false
  get '/dla/franklin/record.html' => 'legacy_franklin#record', :format => false
  get '/dla/franklin' => 'legacy_franklin#redirect_to_root', :format => false
  get '/dla/franklin/*any' => 'legacy_franklin#dla_subpaths', :format => false

  root to: "catalog#landing"
  get 'bento/' => 'catalog#bento'
  get 'databases', to: 'catalog#databases'
  get 'stackmap/fisher', to: 'stackmap#fisher'
  get 'stackmap/van-pelt', to: 'stackmap#vanpelt'

  mount Blacklight::Engine => '/'
  mount BlacklightDynamicSitemap::Engine => '/'


  mount BlacklightAdvancedSearch::Engine => '/'

  #####
  # the reverse routes in blacklight_advanced_search/_facet_limit.html.erb
  # don't work unless these routes exist
  #####
  get 'advanced' => 'advanced#index'
  get 'advanced/facet' => 'advanced#facet'

  get 'collection_news' => 'collection_news#index'

  get 'known_issues' => 'application#known_issues'

  Blacklight::Marc.add_routes(self)
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  # override devise's sessions controller w/ our own
  devise_for :users, controllers: { sessions: 'sessions' }

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  # Items API
  get 'alma/items/:mms_id/all', to: 'items#all'
  get 'alma/bib/:mms_id/holding/:holding_id/item/:item_pid', to: 'items#one'

  # New Requesting Actions
  get 'request/confirm/:type', to: 'requests#confirm'
  get 'request/options', to: 'requests#options'
  post 'request/submit', to: 'requests#submit'

  get 'alma/availability' => 'franklin_alma#availability'
  get 'alma/single_availability' => 'franklin_alma#single_availability'
  get 'alma/holding_items' => 'franklin_alma#holding_items'
  get 'alma/holding_details' => 'franklin_alma#holding_details'
  get 'alma/portfolio_details' => 'franklin_alma#portfolio_details'
  get 'alma/request_options' => 'franklin_alma#request_options'
  get 'alma/check_requestable' => 'franklin_alma#check_requestable'

  get 'alma/request' => 'franklin_alma#load_request'
  post 'alma/request' => 'franklin_alma#create_request'

  devise_scope :user do
    get 'alma/social_login_callback' => 'sessions#social_login_callback'
    get 'accounts/login' => 'sessions#sso_login_callback'
  end

  if ENV['ENABLE_DEBUG_URLS'] == 'true'
    get '/headers_debug' => 'application#headers_debug'
    get '/session_debug' => 'application#session_debug'
  end

  BentoSearch::Routes.new(self).draw

end

app/controllers/requests_controller.rb
# frozen_string_literal: true

# Requesting actions
class RequestsController < ApplicationController
  before_action :set_item, only: :submit

  def confirm
    partial = partial_for_request_type params
    set_ill_url if partial.in? %w[ill noncirc]
    set_address_info if user_alma_group == 'Faculty Express'
    render "requests/confirm/#{partial}", layout: false
  end

  def submit
    request = AbstractRequest.new @item, user_data, params
    @response = request.submit
    render 'requests/done', layout: false
  end

  def options
    options = TurboAlmaApi::Client.request_options(
      params[:mms_id].to_s, user_id
    )
    render json: options
  end

  private

  def set_item
    @item = if (params[:item_pid] == 'no-item') || params[:item_pid].blank?
              nil
            else
              TurboAlmaApi::Client.item_for mms_id: params[:mms_id].to_s,
                                            holding_id: params[:holding_id].to_s,
                                            item_pid: params[:item_pid].to_s
            end
  end

  def set_address_info
    @address_info = Illiad::ApiClient.new.address_info_for user_id
  end

  # Set the ILL URL for use in the ILL confirmation partial
  # @return [String]
  def set_ill_url
    @ill_url = ill_openurl_from_alma params[:mms_id].to_s
  end

  # Determine partial for modal dialog based on request params
  # @param [ActionController::Parameters] params
  def partial_for_request_type(params)
    case params[:type].to_sym
    when :circulate
      params[:available] ? 'circulate' : 'ill'
    when :noncirc then 'noncirc'
    when :ill then 'ill'
    when :electronic then 'electronic'
    when :aeon then 'aeon'
    else
      # TODO: better error
      raise ArgumentError, I18n.t('requests.messages.invalid_confirm_partial')
    end
  end

  # Get ILL URL from Alma API client
  # @param [String] mms_id
  def ill_openurl_from_alma(mms_id)
    options = TurboAlmaApi::Client.request_options mms_id, user_id
    options.dig('ILLIAD') || ill_request_form_url_for(mms_id)
  end

  # A backup in case we can't get the nice link from Alma
  # @param [String] mms_id
  def ill_request_form_url_for(mms_id)
    URI::HTTPS.build(host: request.host, path: '/redir/ill',
                     query: "requesttype=book&bibid=#{mms_id}&rfr_id=info%3Asid%2Fprimo.exlibrisgroup.com").to_s
  end

  # because current_user is useless
  # @return [Hash{Symbol->String}]
  def user_data
    { id: user_id, email: user_email, group: user_alma_group }
  end

  # @return [String]
  def user_id
    session['id']
  end

  # Email might come from the session, or from a form submission
  # @return [String]
  def user_email
    session['email'] || params['email'].to_s
  end

  # @return [String]
  def user_alma_group
    session['user_group']
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
  # @param [String] mms_id
  # @param [String] holding_id
  # TODO: this will be confusing in non-production environments
  def aeon_request_form_url_for(mms_id, holding_id)
    "https://franklin.library.upenn.edu/redir/aeon?bibid=#{mms_id}&hldid=#{holding_id}"
  end

  def circulate_modal_title
    if user_is_facex?
      t('requests.modal_titles.confirm.facex')
    else
      t('requests.modal_titles.confirm.circulate')
    end
  end

  # @return [Symbol]
  def noncirc_type
    case params[:noncirc]
    when 'reserves' then :reserves
    when 'reference' then :reference
    when 'hsp' then :hsp
    when 'in_house' then :inhouse
    else
      :inhouse
    end
  end

  def circulate_pickup_locations
    return options_for_select TurboAlmaApi::Request::PICKUP_LOCATIONS unless user_is_student?

    options_for_select TurboAlmaApi::Request::PICKUP_LOCATIONS, selected: 'VPLOCKER'
  end
end

app/views/requests/confirm/aeon.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="modal-title" id="aeonModalLabel"><%= t('requests.modal_titles.confirm.aeon') %></div>
    </div>
    <div class="modal-body">
      <p><%= t('requests.messages.aeon_explanation') %></p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('requests.buttons.go_back') %></button>
      <%= link_to t('requests.buttons.request_to_view'), aeon_request_form_url_for(params[:mms_id], params[:holding_id]), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/requests/confirm/circulate.html.erb
<%= bootstrap_form_tag url: request_submit_path, method: :post, remote: true do |f| %>
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="modal-title" id="exampleModalLabel">
        <%= circulate_modal_title %>
      </div>
    </div>
    <div class="modal-body">
      <%= f.hidden_field :item_pid, id: 'requestItemPid' %>
      <%= f.hidden_field :holding_id, id: 'requestHoldingId' %>
      <%= f.hidden_field :mms_id, id: 'requestMmsId' %>

      <%= f.text_field :selection,
                       label: t('requests.fields.selected'),
                       disabled: true %>

      <ul class="list-group">
        <% if user_is_facex? %>
          <%= render('requests/confirm/delivery_options/office', f: f) %>
        <% end %>
        <%= render 'requests/confirm/delivery_options/pickup', f: f %>
        <% unless user_is_courtesy_borrower? %>
          <%= render 'requests/confirm/delivery_options/mail', f: f %>
        <% end %>
      </ul>
      <div id="comments-area">
        <a class="input-toggleable" href="#"><%= t('requests.labels.add_comments') %></a>
        <div class="toggle-field" style="display: none;">
          <%= f.text_area :comments, label: t('requests.fields.comment') %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">
        <%= t('requests.buttons.go_back') %>
      </button>
      <%= f.submit t('requests.buttons.submit'), class: 'btn btn-primary' %>
    </div>
  </div>
</div>
<% end %>

app/views/requests/confirm/electronic.html.erb
<%= bootstrap_form_tag url: request_submit_path, method: :post, remote: true do |f| %>
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="modal-title" id="confirmModalLabel"><%= t('requests.modal_titles.confirm.electronic') %></div>
    </div>
    <div class="modal-body">
      <%= f.hidden_field :item_pid, id: 'requestItemPid' %>
      <%= f.hidden_field :holding_id, id: 'requestHoldingId' %>
      <%= f.hidden_field :mms_id, id: 'requestMmsId' %>
      <%= f.hidden_field :isxn, id: 'requestIsxn' %>
      <%= f.hidden_field :bib_title, id: 'requestBibTitle' %>
      <%= f.hidden_field :delivery, value: Illiad::Request::ELECTRONIC_DELIVERY %>

      <div class="alert alert-danger" role="alert">
        <%= t('requests.delivery_messages.digi_html') %>
      </div>

      <% unless session[:email].present? %>
        <%= f.email_field :email,
                          label: t('requests.fields.email'),
                          required: true
        %>
      <% end %>

      <%= f.text_field :title,
                       label: t('requests.fields.title'),
                       disabled: true %>
      <%= f.text_field :selection,
                       label: t('requests.fields.selected'),
                       disabled: true %>
      <%= f.text_field :section_title,
                       label: t('requests.fields.section_title'),
                       required: true %>
      <%= f.text_field :section_author,
                       label: t('requests.fields.section_author'),
                       required: true %>
      <%= f.text_field :section_pages,
                       label: t('requests.fields.section_pages') %>
      <%= f.text_field :section_volume,
                       label: t('requests.fields.section_volume'),
                       value: params[:volume] %>
      <%= f.text_field :section_issue,
                       label: t('requests.fields.section_issue'),
                       value: params[:issue] %>

      <div id="comments-area">
        <a class="input-toggleable" href="#"><%= t('requests.labels.add_comments') %></a>
        <div class="toggle-field" style="display: none;">
          <%= f.text_area :comments, label: t('requests.fields.comment') %>
        </div>
      </div>

    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('requests.buttons.go_back') %></button>
      <%= f.submit t('requests.buttons.submit'), class: 'btn btn-primary' %>
    </div>
  </div>
</div>
<% end %>

app/views/requests/confirm/ill.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="modal-title" id="exampleModalLabel"><%= t('requests.modal_titles.confirm.ill') %></div>
    </div>
    <div class="modal-body">
      <p>
        <%= t('requests.messages.unavailable_prompt') %>
      </p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('requests.buttons.go_back') %></button>
      <%= link_to t('requests.buttons.ill_request'), @ill_url, target: '_blank', class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/requests/confirm/noncirc.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="modal-title" id="exampleModalLabel">Item has Limited Access</div>
    </div>
    <div class="modal-body">
      <div class="alert alert-danger">
        <%= t(noncirc_type, scope: 'requests.messages.noncirc', library: sanitize(params[:library])).html_safe %>
      </div>
      <p>
        If you would like to receive a physical copy, you may try submitting an Interlibrary Loan (ILL) request using
        the button below.
      </p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('requests.buttons.close') %></button>
      <%= link_to t('requests.buttons.ill_request'), @ill_url, target: '_blank', class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/requests/confirm/reserves.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="modal-title" id="exampleModalLabel">Item has Limited Access</div>
    </div>
    <div class="modal-body">
      <p>
        This item is being held at <%= params[:library] %>. It may be checked out for a limited period by visiting
        the library.
      </p>
      <p>
        If you would like to receive a physical copy, you may try submitting an Interlibrary Loan request using the
        button below.
      </p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('requests.buttons.close') %></button>
      <%= link_to t('requests.buttons.ill_request'), @ill_url, target: '_blank', class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/requests/confirm/sad.html.erb
<%= bootstrap_form_tag url: request_submit_path, method: :post do |f| %>

  <%= f.hidden_field :item_pid, id: 'requestItemPid' %>
  <%= f.hidden_field :holding_id, id: 'requestHoldingId' %>
  <%= f.hidden_field :mms_id, id: 'requestMmsId' %>
  <%= f.hidden_field :delivery_method, id: 'requestDeliveryMethod' %>

  <div class="alert alert-warning">
    <%= t('requests.delivery_messages.digi_html') %>
  </div>

  <%= f.text_field :selection,
                   label: 'Selection',
                   disabled: true %>
  <%= f.text_field :section_title,
                   label: t('requests.fields.section_title'),
                   help: t('requests.help.section_title'),
                   required: true %>
  <%= f.text_field :section_author,
                   label: t('requests.fields.section_author'),
                   help: t('requests.help.section_author'),
                   required: true %>
  <%= f.text_field :section_pages,
                   label: t('requests.fields.section_pages'),
                   help: t('requests.help.section_pages') %>
  <%= f.text_field :section_volume,
                   label: t('requests.fields.section_volume'),
                   help: t('requests.help.section_volume'),
                   value: params[:volume] %>
  <%= f.text_field :section_issue,
                   label: t('requests.fields.section_issue'),
                   help: t('requests.help.section_issue'),
                   value: params[:issue] %>

  <a href="#" id="toggle-proxy-input">Proxy Request?</a>

  <div class="proxy-input hidden">
    <%= f.text_field :deliver_to, label: 'Deliver To' %>
  </div>
  
<% end %>