config/routes.rb
Rails.application.routes.draw do
  concern :exportable, Blacklight::Routes::Exportable.new

  # redirects for legacy DLA Franklin links

  get 'index.html' => 'legacy_franklin#redirect_to_root', :format => false
  get 'record.html' => 'legacy_franklin#record', :format => false
  # blacklight_advanced_search has an /advanced route but we never use advanced.html (w/ the format)
  # so this is safe to list here.
  get 'advanced.html' => 'legacy_franklin#redirect_to_root', :format => false
  get '/dla/franklin/record.html' => 'legacy_franklin#record', :format => false
  get '/dla/franklin' => 'legacy_franklin#redirect_to_root', :format => false
  get '/dla/franklin/*any' => 'legacy_franklin#dla_subpaths', :format => false

  root to: "catalog#landing"
  get 'bento/' => 'catalog#bento'
  get 'databases', to: 'catalog#databases'
  get 'stackmap/fisher', to: 'stackmap#fisher'
  get 'stackmap/van-pelt', to: 'stackmap#vanpelt'

  mount Blacklight::Engine => '/'
  mount BlacklightDynamicSitemap::Engine => '/'


  mount BlacklightAdvancedSearch::Engine => '/'

  #####
  # the reverse routes in blacklight_advanced_search/_facet_limit.html.erb
  # don't work unless these routes exist
  #####
  get 'advanced' => 'advanced#index'
  get 'advanced/facet' => 'advanced#facet'

  get 'collection_news' => 'collection_news#index'

  get 'known_issues' => 'application#known_issues'

  Blacklight::Marc.add_routes(self)
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  # override devise's sessions controller w/ our own
  devise_for :users, controllers: { sessions: 'sessions' }

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  # Items API
  get 'alma/items/:mms_id/all', to: 'items#all'
  get 'alma/bib/:mms_id/holding/:holding_id/item/:item_pid', to: 'items#one'

  # New Requesting Actions
  get 'request/confirm/:type', to: 'requests#confirm'
  get 'request/options', to: 'requests#options'
  post 'request/submit', to: 'requests#submit'

  get 'alma/availability' => 'franklin_alma#availability'
  get 'alma/single_availability' => 'franklin_alma#single_availability'
  get 'alma/holding_items' => 'franklin_alma#holding_items'
  get 'alma/holding_details' => 'franklin_alma#holding_details'
  get 'alma/portfolio_details' => 'franklin_alma#portfolio_details'
  get 'alma/request_options' => 'franklin_alma#request_options'
  get 'alma/check_requestable' => 'franklin_alma#check_requestable'

  get 'alma/request' => 'franklin_alma#load_request'
  post 'alma/request' => 'franklin_alma#create_request'

  devise_scope :user do
    get 'alma/social_login_callback' => 'sessions#social_login_callback'
    get 'accounts/login' => 'sessions#sso_login_callback'
  end

  if ENV['ENABLE_DEBUG_URLS'] == 'true'
    get '/headers_debug' => 'application#headers_debug'
    get '/session_debug' => 'application#session_debug'
  end

  BentoSearch::Routes.new(self).draw

end

app/views/shared/_flash_messages.html.erb
<div class="row"> <!-- #EXTRACT:candidate Xapp/views/shared/_flash_messages.html.erb -->
  <div class="col-md-12">
    <div id="main-flashes">
      <%= yield %>
    </div>
    <%# franklin-alerts is for http://www.library.upenn.edu/scripts/franklin_alerts.js to use %>
    <div id="franklin-alerts"></div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer" id="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-3 one">

        <h2>Penn Libraries</h2>

        <ul class="footerlinks">

          <li id="chooselibrarylink"><!-- 2 -->
            <a class="library-home-link" href="https://www.library.upenn.edu">Library Home</a>
          </li>
          <li><a href="https://www.library.upenn.edu/about/locations">Libraries &amp; Hours</a></li>

          <li><a href="<%= resourcesharing_path %>">BorrowDirect+/ILL</a></li>
          <li><a href="https://libcal.library.upenn.edu/appointments">Make an appointment</a></li>

        </ul>

      </div>

      <div class="col-sm-3 two">

        <h2>Franklin Help</h2>

        <ul class="footerlinks">

          <li><a href="https://guides.library.upenn.edu/franklinaccount" target="_blank">Your Library Account</a></li>

          <li><a href="https://guides.library.upenn.edu/franklincatalog">Using Franklin Catalog</a></li>

          <li><a href="https://guides.library.upenn.edu/articlesplus">Using Franklin Articles+</a></li>

          <li><a href="https://guides.library.upenn.edu/usingeresources">Accessing E-Resources</a></li>
        </ul>

      </div>

      <div class="col-sm-3 three">

        <h2>CONTACT US</h2>
        <ul class="footerlinks">
          <li><a href="https://faq.library.upenn.edu/ask">Questions or comments</a></li>
          <% unless current_page?(root_path) %>
            <li id="footerchat">
              <div id="libchat_424b3bc441c9bd760d26a2d0dd03c906"></div><script type="text/javascript" src="//v2.libanswers.com/load_chat.php?hash=424b3bc441c9bd760d26a2d0dd03c906"></script>
            </li>
          <% end %>

        </ul>

      </div>

    </div>

    <div class="row">
      <div class="copyright col-sm-12">&copy; <a href="https://www.upenn.edu/">University of Pennsylvania</a></div>
    </div>

  </div>

</footer>

app/views/shared/_header_navbar.html.erb
<ul id="skip-link">
    <% if current_user %>
    <li><a href="#logout-button" class="element-invisible element-focusable">Log out</a></li>
    <% else %>
    <li><a href="#login-button" class="element-invisible element-focusable">Franklin login</a></li>
    <% end %>
    <li><a href="#a-search" class="element-invisible element-focusable">Active search</a></li>
    <li><a href="#search-options" class="element-invisible element-focusable">Search options</a></li>
    <li><a href="#main-container" class="element-invisible element-focusable">Main content</a></li>
</ul>
<header>


  <div id="navandidbar" class="clearfix">
      <h2 class="visually-hidden">Login, libraries-wide information</h2>

      <!-- LOGIN -->
      <% if has_user_authentication_provider? %>
          <ul class="nav navbar-nav">

            <% if current_user %>
                <li class="nameuser">
                    <a href="<%= my_library_card_url %>"><% if session['first_name'].present? %><span class="user-first-name"><%= session['first_name'] %> - </span><% end %>My Library Account</a>
                </li>
                <li class="destroysession">
                    <button id="logout-button" type="button" class="btn btn-default btn-sm"><%= link_to t('blacklight.header_links.logout'), destroy_user_session_path %></button>
                </li>
            <% else %>
                <li class="loginbutton">
                  <div class="navbar-btn-group btn-group">
                    <button id="login-button" type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Login <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                      <li class="small"><a href="<%= accounts_login_url(next: request.original_url) %>"><span class="desktop">Current faculty, student, staff login</span><span class="mobile">PennKey patrons</span></a></li>
                      <li role="separator" class="divider"></li>
                      <li class="small"><a href="https://guides.library.upenn.edu/franklinaccount#s-lg-box-19646803"><span class="desktop">Subscribed alumni and courtesy user login</span><span class="mobile">Subscribed patrons</span></a></li>
                    </ul>
                  </div>

                  <%# = link_to t('blacklight.header_links.login'), new_user_session_path %>
                </li>
            <% end %>
          </ul>
      <% end %>
      <!-- END LOGIN -->

  </div>
  <!-- END NAVANDIDBAR  -->
  <div id="header-navbar" class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="<%= container_classes %>">


        <div class="navbar-header">
            <div id="logobg">
               <a href="https://www.library.upenn.edu" class="logolink lib"><%= image_tag("spacer.gif", :alt => "Penn Libraries home", :class => "logoimg lib") %></a>
               <a href="/" class="logolink franklin"><%= image_tag("spacer.gif", :alt => "Franklin home", :class => "logoimg lib") %></a>
            </div>
        </div><!-- end navbar header -->




      </div><!-- end container -->
  </div>
  <div id="search-navbar" class="navbar navbar-default navbar-static-top" role="navigation">

    <div class="<%= container_classes %>">

      <%= render_search_bar  %>
    </div>
  </div>
</header>