config/routes.rb
Rails.application.routes.draw do
  concern :exportable, Blacklight::Routes::Exportable.new

  # redirects for legacy DLA Franklin links

  get 'index.html' => 'legacy_franklin#redirect_to_root', :format => false
  get 'record.html' => 'legacy_franklin#record', :format => false
  # blacklight_advanced_search has an /advanced route but we never use advanced.html (w/ the format)
  # so this is safe to list here.
  get 'advanced.html' => 'legacy_franklin#redirect_to_root', :format => false
  get '/dla/franklin/record.html' => 'legacy_franklin#record', :format => false
  get '/dla/franklin' => 'legacy_franklin#redirect_to_root', :format => false
  get '/dla/franklin/*any' => 'legacy_franklin#dla_subpaths', :format => false

  root to: "catalog#landing"
  get 'bento/' => 'catalog#bento'
  get 'databases', to: 'catalog#databases'
  get 'stackmap/fisher', to: 'stackmap#fisher'
  get 'stackmap/van-pelt', to: 'stackmap#vanpelt'

  mount Blacklight::Engine => '/'
  mount BlacklightDynamicSitemap::Engine => '/'


  mount BlacklightAdvancedSearch::Engine => '/'

  #####
  # the reverse routes in blacklight_advanced_search/_facet_limit.html.erb
  # don't work unless these routes exist
  #####
  get 'advanced' => 'advanced#index'
  get 'advanced/facet' => 'advanced#facet'

  get 'collection_news' => 'collection_news#index'

  get 'known_issues' => 'application#known_issues'

  Blacklight::Marc.add_routes(self)
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  # override devise's sessions controller w/ our own
  devise_for :users, controllers: { sessions: 'sessions' }

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  # Items API
  get 'alma/items/:mms_id/all', to: 'items#all'
  get 'alma/bib/:mms_id/holding/:holding_id/item/:item_pid', to: 'items#one'

  # New Requesting Actions
  get 'request/confirm/:type', to: 'requests#confirm'
  get 'request/options', to: 'requests#options'
  post 'request/submit', to: 'requests#submit'

  get 'alma/availability' => 'franklin_alma#availability'
  get 'alma/single_availability' => 'franklin_alma#single_availability'
  get 'alma/holding_items' => 'franklin_alma#holding_items'
  get 'alma/holding_details' => 'franklin_alma#holding_details'
  get 'alma/portfolio_details' => 'franklin_alma#portfolio_details'
  get 'alma/request_options' => 'franklin_alma#request_options'
  get 'alma/check_requestable' => 'franklin_alma#check_requestable'

  get 'alma/request' => 'franklin_alma#load_request'
  post 'alma/request' => 'franklin_alma#create_request'

  devise_scope :user do
    get 'alma/social_login_callback' => 'sessions#social_login_callback'
    get 'accounts/login' => 'sessions#sso_login_callback'
  end

  if ENV['ENABLE_DEBUG_URLS'] == 'true'
    get '/headers_debug' => 'application#headers_debug'
    get '/session_debug' => 'application#session_debug'
  end

  BentoSearch::Routes.new(self).draw

end

app/controllers/catalog_controller.rb
# frozen_string_literal: true

require 'uri'

class CatalogController < ApplicationController
  include ReplaceInvalidBytes
  include BlacklightAdvancedSearch::Controller
  include Blacklight::Catalog
  include Blacklight::Marc::Catalog
  include Blacklight::Ris::Catalog
  include BlacklightSolrplugins::XBrowse
  include HandleInvalidAdvancedSearch
  include AssociateExpandedDocs
  include EmailActionProtection

  ENABLE_SUBJECT_CORRELATION = ENV['ENABLE_SUBJECT_CORRELATION']&.downcase == 'true'

  # explicitly define solr fields to be returned beyond the stored fields returned by *
  SOLR_FIELDLIST_PARAM = %w[
    *
    id
    cluster_id
    alma_mms_id
    score
    format_a
    full_text_link_text_a
    isbn_isxn
    isbn_a
    oclc_id
    language_a
    title
    title_880_a
    author_creator_a
    author_880_a
    standardized_title_a
    edition
    conference_a
    series
    publication_a
    contained_within_a
    physical_holdings_json
    electronic_holdings_json
    bound_with_ids_a
    marcrecord_text
    recently_added_isort
    hld_count_isort
    prt_count_isort
    empty_hld_count_isort
    itm_count_isort
    nocirc_a
  ].join(',')

  # expire session if needed
  before_action :expire_session

  # screen for illegit sort params
  before_action :block_invalid_sort_params, only: :index

  # establish an effective "record depth" beyond which pagination is not supported
  PAGINATION_THRESHOLD = 10_000
  before_action :limit_index_pagination, only: :index
  before_action :limit_show_pagination, only: :show

  # and also for facets
  FACET_PAGINATION_THRESHOLD = 50
  before_action :limit_facet_pagination, only: :facet

  configure_blacklight do |config|
    # default advanced config values
    config.advanced_search ||= Blacklight::OpenStructWithHashAccess.new
    # config.advanced_search[:qt] ||= 'advanced'
    config.advanced_search[:url_key] ||= 'advanced'
    config.advanced_search[:query_parser] ||= 'perEndPosition_dense_shingle_graphSpans'
    config.advanced_search[:form_solr_parameters] ||= {}


    ## Class for sending and receiving requests from a search index
    # config.repository_class = Blacklight::Solr::Repository
    #
    ## Class for converting Blacklight's url parameters to into request parameters for the search index
    # config.search_builder_class = ::SearchBuilder
    #
    ## Model that maps search index responses to the blacklight response model
    config.response_model = BlacklightSolrplugins::Response

    ## Default parameters to send to solr for all search-like requests. See also SearchBuilder#processed_parameters
    config.default_solr_params = {
        #cache: 'false',
        defType: 'perEndPosition_dense_shingle_graphSpans',
        combo: '{!filters param=$q param=$fq excludeTags=cluster,no_correlation}', # NOTE: $correlation_domain is applied within facets
        presentation_domain: '{!query v=$combo}', # default, overridden for first-class subject_correlation search_field
        post_1928: 'content_max_dtsort:[1929-01-01T00:00:00Z TO *]',
        culture_filter: "{!bool should='{!terms f=subject_search v=literature,customs,religion,ethics,society,social,culture,cultural}' should='{!prefix f=subject_search v=art}'}",
        #combo: '{!bool must=$q filter=\'{!filters param=$fq v=*:*}\'}',
        #combo: '{!query v=$q}',
        # this list is annoying to maintain, but this avoids hard-coding a field list
        # in the search request handler in solrconfig.xml
        fl: SOLR_FIELDLIST_PARAM,
        'facet.threads': 2,
        'facet.mincount': 0,
        #      fq: '{!tag=cluster}{!collapse field=cluster_id nullPolicy=expand size=5000000 min=record_source_id}',
        # this approach needs expand.field=cluster_id
        #cluster: %q~NOT ({!join from=cluster_id to=cluster_id v='record_source_f:"Penn"'} AND record_source_f:"HathiTrust") NOT record_source_id:3~,
        cluster: '{!bool filter=*:* must_not=\'{!bool filter=\\\'{!join from=cluster_id to=cluster_id v=record_source_id:1}\\\' filter=record_source_id:2}\'}',
        back: '{!query v=$correlation_domain}',
        # NOTE: correlation_domain is separately defined from correlation_domain_refine so that the latter may be applied
        # and selectively excluded (via excludeTags) for reporting counts over the full cluster domain, while calculating
        # relatedness over a subset of that domain. This is not always necessary -- e.g., in the case where counts are not
        # needed, such as for "expert help", which can use correlation_domain directly
        correlation_domain: '{!bool filter=$cluster filter=$correlation_domain_refine}',
        correlation_domain_refine: '{!bool filter=elvl_rank_isort:0}',
        fq: '{!query tag=cluster v=$cluster}',
        expand: 'true',
        'expand.field': 'cluster_id',
        'expand.q': '*:*',
        'expand.fq': '*:*',
        rows: 10
    }

    # solr path which will be added to solr base url before the other solr params.
    #config.solr_path = 'select'

    # items to show per page, each number in the array represent another option to choose from.
    config.per_page = [25, 50, 100]

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SearchHelper#solr_doc_params) or
    ## parameters included in the Blacklight-jetty document requestHandler.
    config.default_document_solr_params = {
      expand: 'true',
      'expand.field': 'cluster_id',
      'expand.q': '*:*',
      'fl': SOLR_FIELDLIST_PARAM
    }

    # solr field configuration for search results/index views
    config.index.title_field = 'title'
    # config.index.display_type_field = 'format'
    config.index.document_presenter_class = PennLib::IndexPresenter

    # our custom ShowPresenter: we use this to override the heading
    config.show.document_presenter_class = PennLib::ShowPresenter

    # solr field configuration for document/show views
    #config.show.title_field = 'title_display'
    config.show.display_type_field = 'format_a'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    #
    # set :index_range to true if you want the facet pagination view to have facet prefix-based navigation
    #  (useful when user clicks "more" on a large facet and wants to navigate alphabetically across a large set of results)
    # :index_range can be an array or range of prefixes that will be used to create the navigation (note: It is case sensitive when searching values)

    database_selected = lambda { |a, b, c|
      a.params.dig(:f, :format_f)&.include?(PennLib::Marc::DATABASES_FACET_VALUE)
    }

    # Some filters (e.g., subject_f) are capable of driving meaningful correlations;
    # others are not, and either generate spurious correlations, or at best pointlessly add extra
    # overhead to Solr request.
    # Keys below indicate filters that we should not attempt to use for purpose of cacluating
    # correlations -- either entirely (nil value) or for an array of certain filter values
    # TODO: in search_builder, tag corresponding fq's with `no_correlation` so that they may be
    # excluded from calculation of foreground domains for the purpose of relatedness/correlation
    # calculation.
    CORRELATION_IGNORELIST = {
      :access_f => nil,
      :record_source_f => nil,
      :format_f => [PennLib::Marc::DATABASES_FACET_VALUE]
    }.freeze

    actionable_filters = lambda { |a, b, c|
      params = a.params
      return true if params[:q].present?
      f = params[:f]
      return false if f.nil?
      # we return true if there is at least one non-ignorelisted filter
      return true if f.size > CORRELATION_IGNORELIST.size
      f.symbolize_keys.each do |facet_key, facet_values|
        return true unless CORRELATION_IGNORELIST.include?(facet_key) # no vals are ignored for this key
        ignorelisted_vals = CORRELATION_IGNORELIST[facet_key]
        next unless ignorelisted_vals # all vals are ignored for this key
        return true if (facet_values - ignorelisted_vals).present? # there is at least one non-ignored val
      end
      return false
    }

    search_field_accept = lambda { |field_names, other_conditions = []|
      return lambda { |a, b, c|
        return false unless field_names.include?(a.params[:search_field])
        other_conditions.each do |condition|
          return false unless condition.call(a, b, c)
        end
        return true
      }
    }

    search_field_reject = lambda { |field_names, other_conditions = []|
      return lambda { |a, b, c|
        return false if field_names.include?(a.params[:search_field])
        other_conditions.each do |condition|
          return false unless condition.call(a, b, c)
        end
        return true
      }
    }

app/helpers/catalog_helper.rb
# overrides for blacklight's CatalogHelper
module CatalogHelper
  include Blacklight::CatalogHelperBehavior
  include BlacklightAlma::CatalogOverride

  # @param [Hash] options
  def relevance_score(options)
    values = options[:value]
    "Relevance Score: #{values.first}"
  end
end

app/views/catalog/_alma_availability_iframe.html.erb
<% if display_alma_fulfillment_iframe?(document) %>
<iframe src="<%= alma_app_fulfillment_url(document) %>" title="show availability for this record" class="availability-details-iframe" style="width: 100%"></iframe>
<% end %>

app/views/catalog/_database_search_form.html.erb
  <%= form_tag search_catalog_path, method: :get, class: 'search-query-form clearfix navbar-form', id: 'a-search', 'aria-label': 'search databases', role: 'search' do %>
  <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8)) %>
  <div class="input-group">
    <% if search_fields.length > 1 %>
      <span class="input-group-addon for-search-field">
        <label for="search_field_databases" class="sr-only"><%= t('blacklight.search.form.search_field.label') %></label>
        <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), title: t('blacklight.search.form.search_field.title'), id: "search_field_databases", class: "search_field") %>
      </span>
    <% elsif search_fields.length == 1 %>
      <%= hidden_field_tag :search_field, search_fields.first.last %>
    <% end %>
    <label for="q3" class="sr-only"><%= t('blacklight.search.form.search.label') %></label>
    <%= text_field_tag :q, params[:q], { placeholder: (current_page?(controller: 'advanced') ? 'Configure advanced search below' : t('franklin.databases_search.placeholder')), class: "search_q q form-control", id: "q3", data: { autocomplete_enabled: autocomplete_enabled?, autocomplete_path: blacklight.suggest_index_path } }.merge(current_page?(controller: 'advanced') ? {disabled: 'disabled'} : {})  %>
    <span class="input-group-btn">
      <button type="submit" class="btn btn-primary search-btn" id="search" <%= current_page?(controller: 'advanced') ? 'disabled="disabled"' : ''%>>
        <div title="search" class="mag-bg"><span class="visually-hidden"><%= t('blacklight.search.form.submit') %></span></div>
      </button>
    </span>
  </div>
<% end %>
<% if current_page?(controller: 'advanced') %>
  <div class="navbar-form tools-advanced-bookmarks">
    <%= link_to 'Basic Search', search_catalog_path + '#catalog', class: 'btn btn-default'%>
  </div>
<% else %>
  <div class="navbar-form tools-basic-bookmarks">
    <%= link_to 'Advanced', blacklight_advanced_search_engine.advanced_search_path(search_state.to_h), class: 'advanced_search btn btn-default'%>
    <%= render_nav_actions do |config, action|%>
      <div id="li-bookmarks"><%= action %></div>
    <% end %>
  </div>
<% end %>

app/views/catalog/_expert_help.html.erb
<div class="panel panel-default facet_limit expert-results bento-box" id="bento-results-expert">
  <%= render 'expert_help_header' %>
  <div id="ExpertOptions" class="expert-profile collapse">
    <%= image_tag specialist[:portrait], alt: specialist[:display_name] %>
    <div class="upper-content">
      <%= link_to specialist[:display_name], subject_url(subject), class: 'link-to-profile' %>
      <p class="expert-p"><%= bolded_subject_list(specialist[:subjects], subject).join(', ').html_safe %></p>
      <p class="expert-p">
        <%= mail_to specialist[:email], specialist[:email],
                    body: "I was searching Franklin @ #{request.original_url}" %>
      </p>
    </div>
    <div class="lower-content">
      <hr class="hr-text" data-content="OR">
      <div class="expert-chat-link" id="libchat_7cde980ad423479da2585a498007774e"></div><script src="https://faq.library.upenn.edu/load_chat.php?hash=7cde980ad423479da2585a498007774e"></script>  </div>
    </div>
</div>

app/views/catalog/_expert_help_header.html.erb
<div class="collapse-toggle panel-heading expert-box collapsed" data-toggle="collapse" data-target="#ExpertOptions">
  <h3 class="panel-title facet-field-heading expert-heading">
    <button data-no-turbolink="true" href="#">Expert help</button>
    
  </h3>
</div>

app/views/catalog/_facets_first_class.html.erb
<%= render_facet_partials(facet_field_names(:first_class), :facet_type => :first_class) %>

app/views/catalog/_format_facet.html.erb
<ul class="format-facet facet-values list-unstyled">
  <% paginator = facet_paginator(facet_field, display_facet) %>
  <% paginator.items.each do |item| -%>
    <% next if item.value == item.value.to_i.to_s %>
    <li>
      <span class="icon <%= format_icon(item.value) %>"></span>
      <% if facet_in_params?( solr_field, item.value ) %>
          <%= render_selected_facet_value(solr_field, item) %>
        <% else %>
          <%= render_facet_value(solr_field, item) %>
      <% end -%>
    </li>
  <% end %>
</ul>

app/views/catalog/_index_default.html.erb
<% doc_presenter = index_presenter(document) %>
<%= detect_nocirc(document) %>

<div class="search-results-row row">
  <div class="col-xs-10 col-sm-9 col-md-10">
    <div class="documentHeader">
      <%# main title container for doc partial view
          How many bootstrap columns need to be reserved
          for bookmarks control depends on size.
      -%>

      <h3 class="index_title document-title-heading">
        <% if counter = document_counter_with_offset(document_counter) %>
          <span class="document-counter">
            <%= t('blacklight.search.documents.counter', counter: counter) %>
          </span>
        <% end %>
        <%= link_to_document document, document_show_link_field(document), counter: counter %>
      </h3>
    </div>
    <ul class="document-metadata dl-horizontal dl-invert">
      <% index_fields(document).each do |field_name, field| -%>
          <% if should_render_index_field?(document, field) && field_name != 'full_text_links_for_cluster_display' %>
              <li class="blacklight-<%= field_name.parameterize %>"><%= doc_presenter.field_value field_name %></li>
          <% end -%>
      <% end %>
    </ul>
    <ul class="document-metadata dl-horizontal dl-invert results-availability">
      <% online_field_name = 'full_text_links_for_cluster_display' %>
      <% if doc_presenter.field_value online_field_name %>
          <li class="blacklight-<%= online_field_name.parameterize %>"><%= doc_presenter.field_value online_field_name %></li>
      <% end -%>
      <% if document.alma_mms_id.present? && !atom_request? && document.has_any_holdings? %>
        <li class="blacklight-availability">
          <%= render 'status_location_field', document: document %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-xs-2 col-sm-3 col-md-2">
    <%= render_index_doc_actions document %>
    <div class="cover-image <%= format_icon(document.fetch_format, size: 'large') %>" <%= document.cover_id_attrs %>>
    </div>
  </div>
</div>
<% if (document.alma_mms_id.present? || document.is_pod?) && !atom_request? %>
  <% if document.show_requesting_widget? %>
    <%= render 'requests/index_request_widget', document: document, hide: true %>
  <% elsif document.is_pod? %>
    <%= render 'requests/pod_widget', document: document %>
  <% else %>
    <%= render 'alma_availability', document: document, collapsed: true %>
  <% end %>
<% end %>

app/views/catalog/_landing_bento.html.erb
<div class="sticky-chat">
    <script src="https://faq.library.upenn.edu/load_chat.php?hash=15c79c53182e201520a47857fb3d1e96"></script>
    <div id="libchat_15c79c53182e201520a47857fb3d1e96"></div>
  </div>
<div class="landing-content">

  <div id="sidebar" class="col-md-3 col-sm-4">
    <div class="panel panel-default facet_limit other-links">
      <div class="panel-heading">
        <h2 class="panel-title facet-field-heading">Other resources</h2>
      </div>
      <ul class="facet-values list-unstyled">
        <li><a href="https://franklin.library.upenn.edu/forms/resourcesharing">BorrowDirect / E-ZBorrow</a></li>
        <li><a href="https://www.library.upenn.edu/instruction-and-course-support/course-reserves">Course reserves</a></li>
        <li><a href="https://www.jstor.org/images">JSTOR image collections</a></li>
        <li><a href="https://faq.library.upenn.edu/search/">Library FAQs</a></li>
        <li><a href="https://upenn.alma.exlibrisgroup.com/discovery/citationlinker?vid=01UPENN_INST:Services&lang=en">PennText Article Finder</a></li>
        <li><a href="https://guides.library.upenn.edu/hometabs">Research guides</a></li>
        <li><a href="https://repository.upenn.edu/">ScholarlyCommons</a></li>
        <li><a href="https://www.law.upenn.edu/library/research/catalog-search.php">Search Center (Law Catalog)</a></li>
        <li><a href="https://hdl.library.upenn.edu/1017/7158">WorldCat</a></li>
        <li></li>
      </ul>
    </div>
  </div>

  <div class="col-sm-6 about-blurb">
    <p>
      Search <span class="heading inline">Franklin</span> to explore a wide selection of library print and electronic books, journal and newspaper articles, videos, sound recordings, manuscripts, conference proceedings, and many other resources owned or subscribed to by the Penn Libraries.
    </p>

  </div>
  <div class="col-sm-6">

    <div class="colnews">

      <div class="colnewsheader heading">

        <div class="colnewslabel">

          <div>Collection &nbsp;</div>

        </div>

        <div class="colnewslabelicon" title="news"></div>

      </div>

      <div class="collection-news">
      </div>

      <div class="morenews"><a href="https://www.library.upenn.edu/blogs/libraries-news">More collection news...</a></div>

    </div>

  </div>
</div>

app/views/catalog/_rbrowse_display_fields.html.erb
<%= render 'catalog/index_default', document: doc_presenter.document, document_counter: nil %>

app/views/catalog/_search_form.html.erb
  <%= form_tag search_catalog_path, method: :get, class: 'search-query-form clearfix navbar-form', id: 'a-search', 'aria-label': 'catalog search', role: 'search' do %>

  <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8)) %>
  <div class="input-group">
    <% if search_fields.length > 1 %>
      <span class="input-group-addon for-search-field">
        <label for="search_field" class="sr-only"><%= t('blacklight.search.form.search_field.label') %></label>
        <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), { title: t('blacklight.search.form.search_field.title'), id: "search_field", class: "search_field"}.merge(current_page?(controller: 'advanced') ? {disabled: 'disabled'} : {})) %>
      </span>
    <% elsif search_fields.length == 1 %>
      <%= hidden_field_tag :search_field, search_fields.first.last %>
    <% end %>

    <label for="q1" class="sr-only"><%= t('blacklight.search.form.search.label') %></label>
    <%= text_field_tag :q, params[:q], { placeholder: (current_page?(controller: 'advanced') ? 'Configure advanced search below' : t('blacklight.search.form.search.placeholder')), class: "search_q q form-control", id: "q1", data: { autocomplete_enabled: autocomplete_enabled?, autocomplete_path: blacklight.suggest_index_path } }.merge(current_page?(controller: 'advanced') ? {disabled: 'disabled'} : {})  %>

    <span class="input-group-btn">
      <button type="submit" class="btn btn-primary search-btn" id="search" <%= current_page?(controller: 'advanced') ? 'disabled="disabled"' : ''%>>
        <div title="search" class="mag-bg"><span class="visually-hidden"><%= t('blacklight.search.form.submit') %></span></div>
      </button>
    </span>
  </div>
<% end %>

<% if current_page?(controller: 'advanced') %>
  <div class="navbar-form tools-advanced-bookmarks">
    <%= link_to 'Basic Search', search_catalog_path + '#catalog', class: 'btn btn-default'%>
<% else %>
  <div class="navbar-form tools-basic-bookmarks">
    <%= link_to 'Advanced', blacklight_advanced_search_engine.advanced_search_path(search_state.to_h), class: 'advanced_search btn btn-default'%>
<% end %>
  <%= render_nav_actions do |config, action|%>
          <div id="li-bookmarks"><%= action %></div>
   <% end %>
</div>

app/views/catalog/_search_header.html.erb
<!-- #EXTRACT:candidate Xapp/views/catalog/_search_header.html.erb -->
<%= render 'did_you_mean' %>

<%= render 'constraints' %>

<%= render 'facets_header' %>

<%= render 'sort_and_per_page' %>

app/views/catalog/landing.html.erb
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane <%= active_tab_classes('bento') %>" id="bento-main">
      <%= render partial: 'landing_bento' %>
    </div>
    <div role="tabpanel" class="tab-pane <%= active_tab_classes('catalog') %>" id="catalog-main">
      <%= render partial: 'landing_catalog' %>
    </div>
    <div role="tabpanel" class="tab-pane" id="articles-main">
      <%= render partial: 'landing_articles' %>
    </div>
  </div>

app/views/catalog/nopennkey.html.erb
<%# this page is obsolete, keeping it for historical purposes %>

<h2>No PennKey?</h2>

<p>This page should explain what to do if you don't have a PennKey. TODO.</p>

<p>One option is to <a href="<%= alma_social_login_url %>">login using a Google account</a>.</p>

app/views/catalog/request_created.html.erb
<span>Your request has been submitted. You can view your open requests in your Library Account.</span>