config/routes.rb
Rails.application.routes.draw do
  concern :exportable, Blacklight::Routes::Exportable.new

  # redirects for legacy DLA Franklin links

  get 'index.html' => 'legacy_franklin#redirect_to_root', :format => false
  get 'record.html' => 'legacy_franklin#record', :format => false
  # blacklight_advanced_search has an /advanced route but we never use advanced.html (w/ the format)
  # so this is safe to list here.
  get 'advanced.html' => 'legacy_franklin#redirect_to_root', :format => false
  get '/dla/franklin/record.html' => 'legacy_franklin#record', :format => false
  get '/dla/franklin' => 'legacy_franklin#redirect_to_root', :format => false
  get '/dla/franklin/*any' => 'legacy_franklin#dla_subpaths', :format => false

  root to: "catalog#landing"
  get 'bento/' => 'catalog#bento'
  get 'databases', to: 'catalog#databases'
  get 'stackmap/fisher', to: 'stackmap#fisher'
  get 'stackmap/van-pelt', to: 'stackmap#vanpelt'

  mount Blacklight::Engine => '/'
  mount BlacklightDynamicSitemap::Engine => '/'


  mount BlacklightAdvancedSearch::Engine => '/'

  #####
  # the reverse routes in blacklight_advanced_search/_facet_limit.html.erb
  # don't work unless these routes exist
  #####
  get 'advanced' => 'advanced#index'
  get 'advanced/facet' => 'advanced#facet'

  get 'collection_news' => 'collection_news#index'

  get 'known_issues' => 'application#known_issues'

  Blacklight::Marc.add_routes(self)
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  # override devise's sessions controller w/ our own
  devise_for :users, controllers: { sessions: 'sessions' }

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  # Items API
  get 'alma/items/:mms_id/all', to: 'items#all'
  get 'alma/bib/:mms_id/holding/:holding_id/item/:item_pid', to: 'items#one'

  # New Requesting Actions
  get 'request/confirm/:type', to: 'requests#confirm'
  get 'request/options', to: 'requests#options'
  post 'request/submit', to: 'requests#submit'

  get 'alma/availability' => 'franklin_alma#availability'
  get 'alma/single_availability' => 'franklin_alma#single_availability'
  get 'alma/holding_items' => 'franklin_alma#holding_items'
  get 'alma/holding_details' => 'franklin_alma#holding_details'
  get 'alma/portfolio_details' => 'franklin_alma#portfolio_details'
  get 'alma/request_options' => 'franklin_alma#request_options'
  get 'alma/check_requestable' => 'franklin_alma#check_requestable'

  get 'alma/request' => 'franklin_alma#load_request'
  post 'alma/request' => 'franklin_alma#create_request'

  devise_scope :user do
    get 'alma/social_login_callback' => 'sessions#social_login_callback'
    get 'accounts/login' => 'sessions#sso_login_callback'
  end

  if ENV['ENABLE_DEBUG_URLS'] == 'true'
    get '/headers_debug' => 'application#headers_debug'
    get '/session_debug' => 'application#session_debug'
  end

  BentoSearch::Routes.new(self).draw

end

app/views/bento_search/_articles.html.erb
<div class="col col-md-4 col-lg-4 bento-box summon-results ezproxy-login-status" id="bento-results-summon">
  <a name="articles"></a>
  <div class="corner left-top hide"></div>
  <div class="corner right-top hide"></div>
  <h3>Articles+</h3>
  <%= bento_search 'summon', query: query_param_value, per_page: 5, load: :ajax_triggered %>
</div>

app/views/bento_search/_articles_search_form.html.erb
<%= form_tag '', method: :get, class: 'summon-form search-query-form clearfix navbar-form', id: 'a-search', 'aria-label': 'search articles',  role: 'search' do %>
    <div class="input-group">
      <label for="q2" class="sr-only"><%= t('blacklight.search.form.search.label') %></label>
      <%= text_field_tag :q, params[:q], placeholder: t('franklin.articles_search.placeholder'), class: "search_q q form-control", id: "q2", data: { autocomplete_enabled: autocomplete_enabled?, autocomplete_path: blacklight.suggest_index_path }  %>
      <span class="input-group-btn">
      <button type="submit" class="btn btn-primary search-btn" id="search">
        <div title="search" class="mag-bg"><span class="visually-hidden"><%= t('blacklight.search.form.submit') %></span></div>
      </button>
    </span>
    </div>
    <div class="limit-options">
      <div class="checkbox">
        <label>
          <input value="IsScholarly,true,f" name="fvf" id="articleCheckBoxPeerReview" type="checkbox"> Scholarly &amp; peer-review only
        </label>
      </div>
      <div class="checkbox">
        <label>
          <input value="IsFullText,true,f" name="fvf" id="articleCheckBoxFulltext" type="checkbox"> Full text only
        </label>
      </div>
      <div class="checkbox">
        <label>
          <input value="ContentType,Newspaper Article,t" name="fvf" id="articleFilter1" type="checkbox"> Exclude Newspapers
        </label>
      </div>
    </div>
<% end %>
<%= render_nav_actions do |config, action|%>
        <div id="li-bookmarks"><%= action %></div>
 <% end %>

app/views/bento_search/_catalog.html.erb
<div class="col col-md-4 col-lg-4 bento-box catalog-results" id="bento-results-catalog">
  <a name="catalog"></a>
  <h3>Catalog</h3>
  <div class="view-and-filter text-right">
    <%= link_to "View and filter #{number_with_delimiter(@response.total)} #{@response.total  != 1 ? 'results' : 'result'}",
                search_catalog_path(q: params[:q] || params[:query], search_field: 'keyword') %>
  </div>
  <% if @document_list.any? %>
    <%= render 'bento_search/catalog_items' %>
  <% else %>
    <%= t('franklin.catalog_search.no_results') %>
  <% end %>
  <div class="view-all">
    <%= link_to(
            "View all results #{image_tag('view_all_arrow.png', alt: 'View All Results icon')}".html_safe,
            search_catalog_path(q: params[:q] || params[:query], search_field: 'keyword')
        )
    %>
  </div>
</div>

app/views/bento_search/_catalog_item.html.erb
<%# this should receive an iterable _results_ and render an item entry for the bento %>
<% @document_list.each do |result| %>
<div class="bento_item" data-unique-id="<%= result['id'] %>">
  <h4 class="bento_item_title">
    <%= link_to result['title'], solr_document_path(result['id']) %>
  </h4>
  <div class="bento_item_body">
    <dl class="document-metadata dl-horizontal dl-invert">
      <dd>
        <span class="author">
          <%= result['author_creator_a']&.first %>
        </span>
      </dd>
      <dd>
        <span class="publisher">
          <%= result['publication_a']&.first %>
        </span>
      </dd>
      <dd>
        <span class="format">
          <%= result['format_a']&.first %>
        </span>
      </dd>
      <% if online_holding_info = online_holding_info_for(result) %>
      <dd><%= online_holding_info %></dd>
      <% end %>
      <% if result.print_holdings? %>
      <dd><%= print_holding_info_for result %></dd>
      <% end %>
    </dl>
  </div>
</div>
<% end %>
<div class="view-all">
  <%= link_to(
        "View all results #{image_tag('view_all_arrow.png', alt: 'View All Results icon')}".html_safe,
        search_catalog_path(q: params[:q] || params[:query], search_field: 'keyword')
      )
  %>
</div>

app/views/bento_search/_catalog_items.html.erb
<% @document_list.each do |result| %>
<div class="bento_item" data-unique-id="<%= result['id'] %>">
  <h4 class="bento_item_title">
    <%= link_to result['title'], solr_document_path(result['id']) %>
  </h4>
  <div class="bento_item_body">
    <dl class="document-metadata dl-horizontal dl-invert">
      <dd>
        <span class="author">
          <%= result['author_creator_a']&.first %>
        </span>
      </dd>
      <dd>
        <span class="publisher">
          <%= result['publication_a']&.first %>
        </span>
      </dd>
      <dd>
        <span class="format">
          <%= result['format_a']&.first %>
        </span>
      </dd>
      <% if online_holding_info = online_holding_info_for(result) %>
      <dd><%= online_holding_info %></dd>
      <% end %>
      <% if result.print_holdings? %>
      <dd><%= print_holding_info_for result %></dd>
      <% end %>
    </dl>
  </div>
</div>
<% end %>

app/views/bento_search/_colenda.html.erb
<div class="bento-box colenda-results" id="bento-results-colenda">
  <a name="colenda"></a>
  <div class="corner left-top hide"></div>
  <div class="corner right-top hide"></div>
  <h3>Colenda <%=link_to("(What is Colenda?)", "https://colenda.library.upenn.edu/pages/about", class: "colenda-help") %></h3>
  <%= bento_search 'colenda', query: query_param_value, load: :ajax_auto %>
</div>

app/views/bento_search/_databases.html.erb
<div class="bento-box databases-results" id="bento-results-databases">
  <a name="databases"></a>
  <h3>Databases</h3>
  <%= bento_search 'databases', query: query_param_value, load: :ajax_auto %>
</div>

app/views/bento_search/_search_form.html.erb
<%= form_tag bento_url, method: :get, class: 'search-query-form clearfix navbar-form', id: 'a-search', 'aria-label': 'search everything', role: 'search' do %>
    <div class="input-group">
      <label for="q" class="sr-only"><%= t('blacklight.search.form.search.label') %></label>
      <%= text_field_tag :q, params[:q], placeholder: t('franklin.bento_search.placeholder'), class: "search_q q form-control", id: "q", data: { autocomplete_enabled: autocomplete_enabled?, autocomplete_path: blacklight.suggest_index_path }  %>
      <span class="input-group-btn">
      <button type="submit" class="btn btn-primary search-btn" id="search">
        <div title="search" class="mag-bg"><span class="visually-hidden"><%= t('blacklight.search.form.submit') %></span></div>
      </button>
    </span>
    </div>
<% end %>
<!-- everything -->
<%= render_nav_actions do |config, action|%>
        <div id="li-bookmarks"><%= action %></div>
<% end %>

app/views/bento_search/_std_item.html.erb
<%# this overrides the partial in bento_search gem %>

<% bento_decorate(item) do |item| %>

    <%# for debugging purposes, we'll include the vendor-specific unique_id, if we have
      one, in a data-unique-id attribute. %>

    <div class="bento_item" data-unique-id="<%= item.unique_id %>">
      <%= render :partial => "bento_search/item_title", :object => item, :as => 'item' %>

      <div class="bento_item_body">
        <dl class="document-metadata dl-horizontal dl-invert">

          <% if item.custom_data['thumbnail'].present? %>
            <dd class="colenda-thumbnail"><%= link_to(image_tag(item.custom_data['thumbnail']), item.link) %></dd>
          <% end %>

          <% if item.authors.present? %>
            <dd><%= item.render_authors_list %></dd>
          <% end %>

          <% if item.has_source_info? %>
            <dd class="source-info"><%= item.render_source_info %></dd>
          <% end %>

          <% if item.display_format.present? %>
              <dd><%= item.display_format %></dd>
          <% end %>

          <% if item.display_date.present? %>
            <dd><%= item.display_date %></dd>
          <% end %>

          <% if item.abstract %>
            <dd><%= item.render_summary %></dd>
          <% end %>

          <% if item.other_links.present? %>
            <dd><%= render_other_links(item.other_links) %></dd>
          <% end %>

          <%=  %>

          <% if item.custom_data['holdings'].present? %>
            <dd><%= link_to(item.custom_data['holdings'], "#{item.link}#franklin-availability") %></dd>
          <% end %>
        </dl>

      </div>

    </div>

<% end %>

app/views/bento_search/_website.html.erb
<div class="bento-box google-results" id="bento-results-google">
  <a name="website"></a>
  <div class="corner left-top hide"></div>
  <div class="corner right-top hide"></div>
  <h3>Library website</h3>
  <div class="view-and-filter text-right">
    <%= link_to "View all results", google_site_search_results_url(query_param_value) %>
  </div>
  <script>
      (function() {
          var cx = '015171683814554281596:8nln-kjivsc';
          var gcse = document.createElement('script');
          gcse.type = 'text/javascript';
          gcse.async = true;
          gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(gcse, s);
      })();
  </script>
  <gcse:searchresults-only webSearchResultSetSize="5"></gcse:searchresults-only>
  <div class="view-all">
    <%= link_to(("View all results #{image_tag('view_all_arrow.png')}").html_safe, google_site_search_results_url(query_param_value)) %>
  </div>
</div>